###

POST http://localhost:8000/api/product
Content-Type: application/json

{
     "categoryId": null,
     "productName": "Desk",
     "price" : 100.65,
     "salePercent": 10,
     "quantityInStock": 10,
     "brandId": 101,
     "descriptions": "this desk is a ...",
     "thumbImage":null,
     "saleFinishDate": null,
     "createtAt": null
     
}

###

PUT http://localhost:8000/api/product/1
Content-Type: application/json

{
     "productName": "Gaduur kurtka",
     "price": "77"
}
###

DELETE http://localhost:8000/api/product/1
Content-Type: application/json

###
GET  http://localhost:8000/api/product/1
Content-Type: application/json

###
GET  http://localhost:8000/api/product/100
Content-Type: application/json